<a href="https://colab.research.google.com/github/Damini-Genzeon/GenAI-2024-python/blob/main/Arithmetic_operations_in_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

var = np.array([1,4,9,16])
print("max : ",np.max(var),np.argmax(var))
print("min : ",np.min(var),np.argmin(var))
print("sqrt : ",np.sqrt(var))




max :  16 3
min :  1 0
sqrt :  [1. 2. 3. 4.]


In [5]:
var1 = np.array([[1,2,3],[9,5,6]])
print(np.min(var1,axis=1)) # gives minimun among rows
print(np.min(var1,axis=0)) # gives minimun among coloums

[1 5]
[1 2 3]


# Sin() and Cos()

In [8]:
var2 = np.array([1,2,3])

print(np.sin(var2))
print(np.cos(var2))


[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]


Cumulative Sum

In [10]:
var2 = np.array([1,2,3,4])

print(np.cumsum(var2))

[ 1  3  6 10]
