<a href="https://colab.research.google.com/github/Damini-Genzeon/GenAI-2024-python/blob/main/Arithmetic_Operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1-D Array


In [1]:
import numpy as np
var  = np.array([1,2,3,4])
varadd = var+3
print(varadd)

[4 5 6 7]


In [7]:
var  = np.array([1,2,3,4])
varadd = np.add(var,3)
print(varadd)

[4 5 6 7]


In [2]:
var1  = np.array([1,2,3,4])
var2  = np.array([1,2,3,4])

varadd = var1+var2
print(varadd)

[2 4 6 8]


In [6]:
var1  = np.array([1,2,3,4])
var2  = np.array([1,2,3,4])

varadd = np.add(var1,var2)
print(varadd)

[2 4 6 8]


In [3]:
var1  = np.array([1,2,3,4])
var2  = np.array([1,2,3,4])

varadd = var1-var2
print(varadd)

[0 0 0 0]


In [4]:
var1  = np.array([1,2,3,4])
var2  = np.array([1,2,3,4])

varadd = var1*var2
print(varadd)

[ 1  4  9 16]


In [5]:
var1  = np.array([1,2,3,4])
var2  = np.array([1,2,3,4])

varadd = var1/var2
print(varadd)

[1. 1. 1. 1.]


In [13]:
# reciprocal()
var = np.array([1,2,3,4])

reciprocal_array = np.reciprocal(var)

print(reciprocal_array)


[1 0 0 0]


# 2-D Array

In [10]:
var21  = np.array([[1,2,3,4],[1,2,3,4]])
var22  = np.array([[1,2,3,4],[1,2,3,4]])

print(var21)
print()
print(var22)
print()

varadd = var21+var22

print(varadd)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]
