<a href="https://colab.research.google.com/github/Damini-Genzeon/GenAI-2024-python/blob/main/Data_types_of_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

change data type

In [2]:
import numpy as np
x1 = np.array([1,2,3,4],dtype= "f")
print("Data Type : ",x1.dtype)
print(x1)

Data Type :  float32
[1. 2. 3. 4.]


Use Datatype as function

In [4]:
x2 = np.array([1,2,3,4])

new = np.float32(x2)

print("data type of x2 :",x2.dtype)
print("data type of new :",new.dtype)

print(x2)
print(new)

data type of x2 : int64
data type of new : float32
[1 2 3 4]
[1. 2. 3. 4.]


astype() function

In [5]:
x3 = np.array([1,2,3,4])

new_1 = x3.astype(float)

print(x3)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]
