<a href="https://colab.research.google.com/github/Damini-Genzeon/GenAI-2024-python/blob/main/Numpy_array_shape_and_reshaping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Shape

In [2]:
import numpy as np

var = np.array([[1,2,3,4],[1,2,3,4]])

print(var)
print()
print(var.shape)

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


multi-dimensional

In [4]:
var1 = np.array([1,2,3,4], ndmin=4)
print(var1)
print(var1.ndim)
print()
print(var1.shape)

[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


reshape function = for changing dimensions of array

In [6]:
var2 = np.array([1,2,3,4,5,6])

print(var2)
print(var2.ndim)
print()

x = var2.reshape(3,2) # number of rows, number of coloums

print(x)
print(x.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [9]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(var3)
print(var3.ndim)
print()

x = var3.reshape(2,3,2) # number of rows, number of coloums

print(x)
print(x.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [10]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(var3)
print(var3.ndim)
print()

x1 = var3.reshape(2,3,2) # number of rows, number of coloums

print(x)
print(x.ndim)

print()

one = x1.reshape(-1) # converts into one dimension
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
